name: dagger
on:
  push:

jobs:
  functionTest:
    strategy:
      matrix:
        module: [syft]
    name: call functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Call Dagger Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.10.2"
          verb: functions
          module: ${{ matrix.module }}

